// <auto-generated />
using System;
using CMD.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CMD.DataAccess.Migrations
{
    [DbContext(typeof(CMDWebApiContext))]
    [Migration("20211224133028_migrationfirst")]
    partial class migrationfirst
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("CMD.Entities.ActiveIssues", b =>
                {
                    b.Property<int>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Issues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("patientId")
                        .HasColumnType("int");

                    b.HasKey("IssueId");

                    b.ToTable("ActiveIssues");
                });

            modelBuilder.Entity("CMD.Entities.Allergies", b =>
                {
                    b.Property<int>("AllergieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AllergieName")
                        .HasColumnType("int");

                    b.Property<int>("patientId")
                        .HasColumnType("int");

                    b.HasKey("AllergieId");

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("CMD.Entities.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AppointmentDate")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AppointmentTime")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CommentPublic")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("TypesOfInjury")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("AppointmentId");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("CMD.Entities.Credentials", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CredentialsEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Email");

                    b.HasIndex("CredentialsEmail");

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("CMD.Entities.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DoctorId1")
                        .HasColumnType("int");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NPINo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DoctorId");

                    b.HasIndex("DoctorId1");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("CMD.Entities.DoctorComment", b =>
                {
                    b.Property<string>("CommentPrivate")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.HasKey("CommentPrivate");

                    b.ToTable("DoctorComment");
                });

            modelBuilder.Entity("CMD.Entities.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Q1")
                        .HasColumnType("int");

                    b.Property<int>("Q2")
                        .HasColumnType("int");

                    b.Property<int>("Q3")
                        .HasColumnType("int");

                    b.Property<int>("Q4")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("CMD.Entities.MedicalProblems", b =>
                {
                    b.Property<int>("MedicalProbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("patientId")
                        .HasColumnType("int");

                    b.Property<string>("problem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedicalProbId");

                    b.ToTable("MedicalProblems");
                });

            modelBuilder.Entity("CMD.Entities.Patient", b =>
                {
                    b.Property<int>("Patientid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Doctorid")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasColumnType("nchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Patient_Age")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Patient_BloodGroup")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<DateTime>("Patient_DOB")
                        .HasColumnType("date");

                    b.Property<string>("Patient_Gender")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("Patient_Phno")
                        .IsRequired()
                        .HasColumnType("nchar(64)");

                    b.Property<int?>("Patientid1")
                        .HasColumnType("int");

                    b.HasKey("Patientid");

                    b.HasIndex("Patientid1");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("CMD.Entities.Prescription", b =>
                {
                    b.Property<string>("MedName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("Cycle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DoseStrength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Food")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PrescriptionMedName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("MedName");

                    b.HasIndex("PrescriptionMedName");

                    b.ToTable("Prescription");
                });

            modelBuilder.Entity("CMD.Entities.Symptoms", b =>
                {
                    b.Property<int>("SymtomsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Symptom")
                        .HasColumnType("int");

                    b.HasKey("SymtomsId");

                    b.ToTable("Symptom");
                });

            modelBuilder.Entity("CMD.Entities.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int?>("TestId1")
                        .HasColumnType("int");

                    b.Property<string>("TestName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TestId");

                    b.HasIndex("TestId1");

                    b.ToTable("Test");
                });

            modelBuilder.Entity("CMD.Entities.Vital", b =>
                {
                    b.Property<int>("ECG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Appointment")
                        .HasColumnType("int");

                    b.Property<int>("Diabetes")
                        .HasColumnType("int");

                    b.Property<int>("RespirationRate")
                        .HasColumnType("int");

                    b.Property<int>("Temperature")
                        .HasColumnType("int");

                    b.Property<int?>("VitalECG")
                        .HasColumnType("int");

                    b.HasKey("ECG");

                    b.HasIndex("VitalECG");

                    b.ToTable("Vital");
                });

            modelBuilder.Entity("CMD.Entities.Credentials", b =>
                {
                    b.HasOne("CMD.Entities.Credentials", null)
                        .WithMany("credentials")
                        .HasForeignKey("CredentialsEmail");
                });

            modelBuilder.Entity("CMD.Entities.Doctor", b =>
                {
                    b.HasOne("CMD.Entities.Doctor", null)
                        .WithMany("Doctors")
                        .HasForeignKey("DoctorId1");
                });

            modelBuilder.Entity("CMD.Entities.Patient", b =>
                {
                    b.HasOne("CMD.Entities.Patient", null)
                        .WithMany("Patients")
                        .HasForeignKey("Patientid1");
                });

            modelBuilder.Entity("CMD.Entities.Prescription", b =>
                {
                    b.HasOne("CMD.Entities.Prescription", null)
                        .WithMany("Prescriptions")
                        .HasForeignKey("PrescriptionMedName");
                });

            modelBuilder.Entity("CMD.Entities.Test", b =>
                {
                    b.HasOne("CMD.Entities.Test", null)
                        .WithMany("Tests")
                        .HasForeignKey("TestId1");
                });

            modelBuilder.Entity("CMD.Entities.Vital", b =>
                {
                    b.HasOne("CMD.Entities.Vital", null)
                        .WithMany("Vitals")
                        .HasForeignKey("VitalECG");
                });

            modelBuilder.Entity("CMD.Entities.Credentials", b =>
                {
                    b.Navigation("credentials");
                });

            modelBuilder.Entity("CMD.Entities.Doctor", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("CMD.Entities.Patient", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("CMD.Entities.Prescription", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("CMD.Entities.Test", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("CMD.Entities.Vital", b =>
                {
                    b.Navigation("Vitals");
                });
#pragma warning restore 612, 618
        }
    }
}
